### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by joannekoch**

### CODE REVIEW

**Comment by joefutrelle** [comment]
Looking at the diffs it appears that there are commits on `.txt` files that include deletions and additions that look identical, perhaps only differing in whitespace. Any idea why?

**Comment by joannekoch** [comment]
First of all, the .txt files were committed to this repo & we have not been doing that with other packages.

catvars text file needed this Assemblyline change to column names: attributeName	code	definition
custom units has an added NA.
personnel, keywords & attributes have an extra carriage return at the end of the last line.

whoops... additional_info.txt should not be committed.

**Comment by joefutrelle** [comment]
I think it would be OK to just delete those `.txt` files entirely given our approach with other packages.

**Comment by joannekoch** [comment]
Ok, I'll submit another pull request deleting those text files.

**Comment by sbeaulieu** [comment]
.txt files generated from -info.xls templates can be deleted. The additional_info.txt is stand-alone (like abstract, methods) thus should not be deleted

**Comment by joefutrelle** [comment]
`additional_info.txt` is not present in the release, so IMO we don't need to add one.

**Comment by joannekoch** [comment]
In addition, additional_info.txt is empty in this release.

**Pull request merged**
